### ISSUE TITLE
Algae Container

### ISSUE THREAD

**Issue by DanStaal** [DanStaal/DStaal_UKS_KPBS_Addons#18]
Config update needed.

Habitation/Recycling Info:

| Part                     | PartName                                   | Mass    | Volume   | Seats | Months | Multiplier | EC/s                  | Recycler % | Spreadsheet Approved? |
|:-------------------------|:-------------------------------------------|---------|----------|-------|--------|------------|-----------------------|------------|-----------------------|
| Algae Container          | KKAOSS\_LS\_container\_algae               | 0.5     | 2.4      | 0     | n/a    | n/a        | n/a                   | n/a        | no                    |

**Comment by DanStaal** [comment]
My current thought on this part is that it should produce fertilizer (we had two paths on the forum) and not supplies in base.  (I'm thinking of integrating Soylent support to produce supplies.)

**Comment by DanStaal** [comment]
I've worked up a config for testing with.  (Will commit shortly.)

**Comment by Merkov** [comment]
Okay, so with the changes you've made to the converter ratios, is it safe to call the Algae Container finished?

**Comment by DanStaal** [comment]
I'm still thinking about changing the 'Dry' over to not using Mulch, and I'd like to at least know it's been test-loaded into a game without MKS.  (That is: Just USI-LS.)

Also, are there any balance guidelines for converter switching costs?  I threw some numbers in, but I'm not sure if they mean anything.

So basically: Probably, but I'm being indecisive, because I can be.  ;)

**Comment by Merkov** [comment]
There are actually converter swapping guidelines. I don't know how they work, but for our current dry mode, it says that swapping should cost 10 EC, 10 MaterialKits, and 2 SpecializedParts. 

Also, something just occurred to me: we've made this WAY more powerful than the stock mini ISRU in terms of Ore -> Fertilizer efficiency. If we do decide not to use mulch, we'll have to nerf it.

**Comment by DanStaal** [comment]
Yeah, if we decide to not use mulch, the ratios will change.

Hmm.  Now the question is if we follow the guidelines if we don't know what they are doing.  ;)

**Comment by DanStaal** [comment]
This looks good.
