### ISSUE TITLE
Recycler Container

### ISSUE THREAD

**Issue by DanStaal** [DanStaal/DStaal_UKS_KPBS_Addons#22]
Config update needed.

Habitation/Recycling Info:

| Part                     | PartName                                   | Mass    | Volume   | Seats | Months | Multiplier | EC/s                  | Recycler % | Spreadsheet Approved? |
|:-------------------------|:-------------------------------------------|---------|----------|-------|--------|------------|-----------------------|------------|-----------------------|
| Recycler Container       | KKAOSS\_USI\_Recicler\_g                   | 0.7     | 1.2      | 0     | n/a    | n/a        | 1                     | 60/2       | no                    |

**Comment by Merkov** [comment]
Copied from the USI-LS Information Issue: 

"The Recycler Container will be the first K&K recycler you get. Right now, It's a 60% recycler for 2 kerbals, costs 1 EC/s. This is actually fairly well balanced. The spreadsheet wants the part to be slightly bigger (1.35 vs 1.2), but a lot lighter (0.2 vs 0.7).
...
I had even debated doing something like making the USI recycling container an even lower recycling percentage (40% or so) but making it affect more kerbals (4). That way, the recycling container gets you a greater supply consumption reduction for a large group of kerbals than the water purifier, but the purifier lets you boost that rate. This actually makes the recycling container overpowered for its size [(2.16 vs 1.1)], but still way under for its mass [(0.16 vs 0.7)]." That option would use 0.8 EC/s

What do you think of either of these options?

**Comment by DanStaal** [comment]
Let's keep this one at 60/2, and use the 40/4 for the carbon extractor.  ;)

**Comment by Merkov** [comment]
Uploaded a config file. It's basically the same as what Nils already has, but I changed the stock tech tree node.

**Comment by DanStaal** [comment]
Looks good as is.
