### ISSUE TITLE
Greenhouse

### ISSUE THREAD

**Issue by DanStaal** [DanStaal/DStaal_UKS_KPBS_Addons#23]
Config update needed.

Habitation/Recycling Info:

| Part                     | PartName                                   | Mass    | Volume   | Seats | Months | Multiplier | EC/s                  | Recycler % | Spreadsheet Approved? |
|:-------------------------|:-------------------------------------------|---------|----------|-------|--------|------------|-----------------------|------------|-----------------------|
| Greenhouse               | KKAOSS\_Greenhouse\_g                      | 3.0     | 25       | 2     | 0      | 1.3/2      | 0.525:1               | 35/4       | no                    |

**Comment by Merkov** [comment]
Copied from my chart in the LS Info issue: 

Part|PartName|Mass|Volume|Seats|Months|Multiplier|Supplies Rate|EC/s
----|----|----|----|----|----|----|----|----
Greenhouse|KKAOSS_Greenhouse_g|3|~21|2|n/a|1x3 kerbals|0.00132|2.64/0.75

The conversion rate becomes exactly the same as the Nom-O-Matic 25000-I (they are very similar in size, same crew capacity, Greenhouse's mass is about double) but adds the 1 x 3 kerbal hab multiplier. This makes the mass almost perfect, and the volume either on the low side or the high side depending on if you use the 300% cell thing on the spreadsheet for agriculture modules. 

Edit: While I just updated the config with the numbers from this chart, the above suggested 1.3 x 2 kerbals is also a good fit. It occurs to me that if all of the parts have hab multiplier bonuses for 1 more kerbal than they have seating, you'll never fill them up. I suppose this helps out any kerbals who are in vessels that are docked, though. Especially if I ever find a really nice way to hook a KPBS part to a Tundra multihub. 

As another point, I didn't bother putting in the supply, fertilizer, or mulch storage into the spreadsheet when calculating. I figured since we're bending the "rules" as it is, there wasn't much point. The storage volumes don't play a huge roll in the calculations, anyway.

**Comment by DanStaal** [comment]
There are KPBS parts that have space that don't have hab.  (Airlocks, workrooms, etc.)  So you'll be able to fill it if you want.  Main point is that they overlap...

Anyway, looks good.

**Comment by DanStaal** [comment]
One thought: This part should be able to operate in the other modes under MKS.  What would those ratios be?

**Comment by Merkov** [comment]
I'd have to look them up. MKS lets you use dirt or substrate plus water and fertilizer to make supplies without mulch. I hadn't bothered looking into those yet since I didn't think it really applied to stage 2. I'll see if I can run the numbers tonight.

**Comment by Merkov** [comment]
Okay, later than I expected, but I have a bit of time to peek at the spreadsheet again. 
How would you like this part to look under MKS? Would you still want the greenhouse to always add a hab multiplier, or make it one or the other similar to the way the tundra inflatable habs can be greenhouse efficiency parts or hab parts? 
Balancing this part for MKS, I would do things a bit differently: For USI-LS, I didn't give it any kerbal specialist bonus. For MKS, I would. For USI-LS, I didn't use the agriculture module value thing. For MKS, I would. With that in mind... 

In MKS, the dirt-based supply production ratio is 25 dirt, 25 water, 0.1 fertilizer = 1 supplies. The substrate-based one is 10 substrate, 10 water, 0.1 fertilizer = 1 supplies. 

If I leave the 1 x 3 hab multiplier, we can get a dirt farm using 0.003 dirt, 0.003 water, 0.000012 fertilizer = 0.00012 supplies. 6.13 EC/s. Volume is 21.877, mass is 2.725.

A substrate farm gets 0.003 substrate, 0.003 water, 0.00003 fertilizer, 0.0003 supplies. 6.33 EC/s. Volume for that is 22.863, mass is 2.790

Notice that in these cases, we actually have no enough volume and too much mass, which is the opposite of what we usually run into. Unfortunately, adding machinery doesn't solve this problem (though the spreadsheet does suggest that this module would have roughly 200 machinery to consume). We can play around with what we want to do, but this is sort of what we'd be looking at when it comes time for stage 3.

**Comment by Merkov** [comment]
Just looking at the main USI_LS config (where the greenhouse patch lives): I noticed that the module has this name: 

`name = PlanetaryGreenhouse` 

Is that a proper converter/module name? For comparison, the NOMs use this: 

`name = ModuleResourceConverter_USI` 

Is PlanetaryGreenhouse a K&K module name? If so, should we keep it the way it is, or should we use the USI modules?

**Comment by DanStaal** [comment]
PlanetaryGreenhouse is a K&K module name, I believe.  I wouldn't change it just to change it - but if we want the module-switching to work we'll need ModuleResourceConverter_USI.

**Comment by Merkov** [comment]
So for the base USI-LS patch set, should we change it? I think in base USI-LS it will only have one setting: agroponics + hab multiplier (that is, I don't think we're going to be making it swappable... unless you wanted us to?)

**Comment by DanStaal** [comment]
We could in theory put in the drills as well, and then people would be able to use them since Dirt and Substrate are CRP resources.  No need for all of MKS, they'd have all the parts.  (Though Dirt would likely change behavior if they installed MKS.)

I'm undecided.

**Comment by Merkov** [comment]
Actually, if I was going to do anything swappable with base USI-LS, I was thinking of doing our agroponics + small hab multiplier, swappable to just a powerful hab multiplier. On the one hand, RoverDude did drop that functionality from his NOMs. On the other hand, I feel like we're making KPBS a little more 'involved' than just USI-LS, and the greenhouse is a better shape to make a converter or hab swappable part balanced. 

Again, though, I'm not opposed to just doing the one setup.

**Comment by DanStaal** [comment]
I posted a comment on this in the forum thread - I want to see if anyone else chimes in.

**Comment by DanStaal** [comment]
Had the realization this morning that while adding dirt and substrate to the drills is fine - they'll need them later anyway, and they are general enough that other mods use them - KPBS doesn't have *storage* for those resources.  We do, so only adding those modes to the MKS patch makes sense.

Working on the config now.

**Comment by Merkov** [comment]
Oh yeah. I had completely overlooked that. So do we want to just have the one agro + hab multiplier mode, or do we want to try a agro + hab multiplier as well as a pure hab multiplier mode?

**Comment by DanStaal** [comment]
Config up for the different Greenhouse modes under MKS.  I used your numbers from above, and added in machinery usage of 0.0000040.  (Which I got from the spreadsheet, but I may have been using it incorrectly.)

This won't produce Organics - I think we should dupe this part to create Organics for Stage 3.

I'm not sure if we can swap both agro and hab at the same time, actually...  Which is fine, because I didn't think we should do a pure multiplier for this.  It's a greenhouse - not producing *some* food is wasteful.  I can't see us growing anything non-edible in space.  (Well, non-usuable: I can see growing Aloe or something for for other properties.)

**Comment by DanStaal** [comment]
Current config doesn't work quite right in MKS - the hab is treated as another module that can be swapped in and out.

**Comment by DanStaal** [comment]
Ok, so we can't swap the converters *and* have the hab.  So, time for a rethink.

**Comment by DanStaal** [comment]
Splitting into three parts.
