### ISSUE TITLE
Cupola

### ISSUE THREAD

**Issue by DanStaal** [DanStaal/DStaal_UKS_KPBS_Addons#27]
Config update needed.

Habitation/Recycling Info:

| Part                     | PartName                                   | Mass    | Volume   | Seats | Months | Multiplier | EC/s                  | Recycler % | Spreadsheet Approved? |
|:-------------------------|:-------------------------------------------|---------|----------|-------|--------|------------|-----------------------|------------|-----------------------|
| Cupola                   | KKAOSS\_Cupola\_g                          | 1.75    | ?        | 1     | 0      | 2/2        | 0.09                  | na         | no                    |

**Comment by DanStaal** [comment]
Suggested

| Part                     | PartName                                   | Mass    | Volume   | Seats | Months | Multiplier | 
EC/s                  | Recycler % | Spreadsheet Approved? |
|:-------------------------|:-------------------------------------------|---------|----------|-------|--------|------------|-----------------------|------------|-----------------------|
| Cupola                   | KKAOSS\_Cupola\_g                          | 1.75    | 7.25        | 1     | 0      | 1.75/2        | 0.875                  | na         | no                    |

**Comment by Merkov** [comment]
I would call that basically spreadsheet approved. The suggested mass is over by a mere 0.1 t, but that's more than close enough I think. Also, even though the stock cupola is larger than the K&K one, the K&K one makes much better use of its space, so I like the way this is balanced against it.

**Comment by DanStaal** [comment]
I'm not seeing anything else that needs to be done on this.
