### ISSUE TITLE
USI Recycler

### ISSUE THREAD

**Issue by Merkov** [DanStaal/DStaal_UKS_KPBS_Addons#29]
From the Chart: 

Part|PartName|Mass|Volume|Seats|Months|Multiplier|EC/s|Recycler %|Spreadsheet Approved?
----|----|----|----|----|----|----|----|----|----
Recycler|KKAOSS_USI_Recicler_g|3.5|5.4|0|n/a|n/a|6|70%/6|no

**Comment by Merkov** [comment]
The USI Recycler looks like it's half as long as the MK1 Habitat, so I've given it half the volume. Putting in the numbers that are already used in the Recycler, I get a suggested volume of 7.425, which is bigger than the 5.4 I've come up with. The suggested mass, however, is only 2.1 tonnes. EC/s should be 10.5, though. 

How do you feel about where this fits balance-wise? 0.7 is a pretty decent recycler, and it affects 6 kerbals. On the other hand, it's much bigger than any container, so I'm not too strongly opposed to it. For comparison, the USI LS large recycler is a 79% recycler for 3 kerbals and has a mass of 3.5 t. 

Also, it doesn't look like I have the power to assign issues to projects (or at least, I haven't figured out how yet), but I can move things around in projects. If you wouldn't mind putting this on the board, I would really appreciate it.

**Comment by Merkov** [comment]
Uploaded and modified Nils' config. For now, I've just put it in the same tech tree placement as the proposed placement for the Recycler Container, left the recycler percentage as is at 70% for 6, and increased the EC usage to 10.5/s.

**Comment by DanStaal** [comment]
Ok, I played around with it in the spreadsheet for a while - 0.7 for 6 seems to be the best fit.  This is definitely the high-end recycler from K&K, so we're doing a bit different trade-off from USI, but I'm going to say that's ok.  The mass will mean you don't want to ship it around, but it's fine for a base.

**Comment by Merkov** [comment]
Yeah, I think that all makes sense. Less work for us!

**Comment by DanStaal** [comment]
Ok, this part looks good except for the fact that it's not showing up in the Planetary Base tabs.  (And it needs CLS support.)

**Comment by Merkov** [comment]
If I remember right, CLS support is fairly straightforward. I don't use it myself (though I keep telling myself I should) but I think I can look it up. 

I have NO idea as to why the part isn't showing up in the Planetary Base tabs. According to a post of Nils' from the CCK discussion page [http://forum.kerbalspaceprogram.com/index.php?/topic/149840-discussion-community-category-kit/&do=findComment&comment=2801180](url) it looks like the Planetary Bases tab just looked for any part whose name started with KKAOSS but not KKAOSS_LS. 

Unless you know what the issue is, I'm thinking just asking Nils is the easiest way to sort this. I'm sure it's something simple.

**Comment by DanStaal** [comment]
CLS is straightforward - I was making notes to myself as I was looking at stuff in-game, instead of modifying the files.  ;)

On the naming thing...  Hmm.  That's interesting.  I believe this is the only part with the naming scheme of 'KKAOSS_USI'...

**Comment by Merkov** [comment]
Alright, I'm terrible at making code look normal in GitHub comments, but for CLS, I'm thinking what we need is: 

`@PART[KKAOSS_USI_Recicler_g]:FOR[PlanetarySurfaceStructures]:NEEDS[ConnectedLivingSpace]:HAS[!MODULE[ModuleConnectedLivingSpace]]`
`{`
`    MODULE`
`    {`
`        name = ModuleConnectedLivingSpace`
`        passable = true`
`        impassablenodes = front , back`
`    }`
`}`

This is basically stolen from Nils' CLS patch found in the mod support folder. This makes it match what the habitats have. I believe the front and back nodes are actually what we would call the top and bottom of the structure...

**Comment by DanStaal** [comment]
Yep.  As I said, that was a note to myself - I've already put that into my local copy.  ;)

**Comment by Merkov** [comment]
So, it may have taken me so long to type that bit of code that you replied before I was done... Oops. 

I think you're right about the KKAOSS_USI being unique to the recycler.
